# Generated by Django 2.2.6 on 2019-10-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vines', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vines',
            name='title',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
