# Generated by Django 2.2.6 on 2019-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vines', '0003_auto_20191023_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='vines',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='thumbnails/'),
            preserve_default=False,
        ),
    ]
